### PR TITLE
Exm125

### PR DESCRIPTION
**Pull request by mayerm94**
# Summary
Support for EXM125

## New behavior
EXM125 patient generation and calculation
## Code changes
# Testing guidance
Use https://github.com/projecttacoma/synthea/tree/split_type branch when doing patient generation

### CODE REVIEW

**Comment by mgramigna** [comment]
I'm a little confused. Your Synthea changes revert the properties file to use R4 exporting instead of stu3? But the CQL and everything in this PR is all in STU3. Therefore your makefile won't work as `./synthea/output/fhir_stu3` won't exist. What is the context for these changes? Does it have to do with R4?

**Comment by p9g** [comment]
should https://github.com/projecttacoma/fhir-bundle-calculator/pull/7/commits/9cb79af1ceab2cfa911d2746b8ae19fc3f6cbc97#diff-ab7bf1c110008b37f7ff0ccf4b4062d7R36 be using deqm-test-client?

**Comment by mayerm94** [comment]
> I'm a little confused. Your Synthea changes revert the properties file to use R4 exporting instead of stu3? But the CQL and everything in this PR is all in STU3. Therefore your makefile won't work as `./synthea/output/fhir_stu3` won't exist. What is the context for these changes? Does it have to do with R4?

The reason why you see the "revert" commit is because at the time my Makefile was doing the synthea-patch task so what was in the Synthea.Properties was going to get over-ridden by the patch. The patching no longer happens so I made updated my 'split-type' branch to explicitly use STU3 now. I think the removal of the patching also explains how our master Synthea branch has made it this far without having STU3 enabled.

**Comment by mayerm94** [comment]
> I'm a little confused. Your Synthea changes revert the properties file to use R4 exporting instead of stu3? But the CQL and everything in this PR is all in STU3. Therefore your makefile won't work as `./synthea/output/fhir_stu3` won't exist. What is the context for these changes? Does it have to do with R4?

It's also because I was basing mistakenly basing and PRing my Synthea branch off of `master` instead of off of `abacus`

**Pull request merged**
