### PR TITLE
Add resources to calculate EXM130 and documentation

### PR DESCRIPTION
**Pull request by mayerm94**
# Summary
Add resources to calculate EXM130 and documentation
https://jira.mitre.org/browse/TACOSTRAT-313

Module Created:
image

### CODE REVIEW

**Comment by mgramigna** [comment]
Synthea pull is merged. This can be updated now with projecttacoma/synthea's master branch

**Comment by mgramigna** [comment]
More of an open question to everyone rather than a change request:

I have some concerns about the extensibility of this going forward. With this approach, we will have to create a Makefile for each measure that we have resources for? Copying mostly the same commands and pointing to different resources for certain pieces. Unfortunately I can't off the top of my head offer a perfect solution for splicing out the common behavior and just being able to tell it which measure we are doing (at least not without more effort than needed).

If we stick with this approach however, your README should probably be updated with Makefile instructions rather than bash commands since we have the Makefile on this branch now.

**Comment by losborne** [comment]
@mgramigna agreed about the duplication--my idea was to get at least one Makefile through review and then DRY it out if that approach was determined to be valuable.  I think it makes sense to leave the duplicated one for this sprint perhaps add a task perhaps for next sprint to make it a bit cleaner, since there are no other measures in the current sprint.  It also doesn't have to stay a Makefile if some other automating structure makes more sense.  It could be an npm script, or a class, or something else.

**Comment by mgramigna** [comment]
Looks good to me, just needs a rebase

**Comment by mgramigna** [comment]
Make sure to include Luke's changes to his Makefile that points to the new file locations for the connecathon repo as well

**Comment by mgramigna** [comment]
Looks good. Needs a re-approval from @losborne since changes were requested

**Pull request merged**
